#!/usr/bin/env php
<?php
use Tricolore\Console\Version;
use Symfony\Component\Console\Application;

require_once __DIR__  . '/../vendor/autoload.php';

$application = new Application();
$application->add(new Version());
$application->run();
