#!/usr/bin/env php
<?php
use Tricolore\Foundation\Application;
use Tricolore\Console\Version;
use Tricolore\Console\RebuildTransUnitId;
use Tricolore\Console\CacheClear;
use Symfony\Component\Console\Application as ConsoleApp;

require __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
require __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '.helpers.php';

umask(0000);

Application::register([
    'directory' => __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR,
    'environment' => 'dev',
    'in_cli' => true
]);

$application = new ConsoleApp();
$application->add(new Version());
$application->add(new RebuildTransUnitId());
$application->add(new CacheClear());
$application->run();
